language: node_js
node_js:
- 12

services:
  - docker
  
script:
- docker run -d -p 8080:8080 u1ih/nodejs-api

after_success:
  - curl -X POST https://api.telegram.org/bot1311265513:AAFTQI69Oh1e5w7SjYTiDiyb_SHy6iQ2P6U/sendMessage -d chat_id=-348620790 -d "text=Build Succeed"

after_failure:
  - curl -X POST https://api.telegram.org/bot1311265513:AAFTQI69Oh1e5w7SjYTiDiyb_SHy6iQ2P6U/sendMessage -d chat_id=-348620790 -d "text=Build Failed"
